version: '3'

services:
  db:
    container_name: timesheet-database
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    env_file:
      - '../src/settings/.env'

volumes:
  mongodb-data:
