version: '3'

services:
  budget:
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/my.cnf
    container_name: time-sheet-db

volumes:
  mysql-data: